name: Generator Auto

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      account:
        description: 'Number of Accounts to be generated (default = 0)'
        required: false
        default: '0'
      key:
        description: 'Number of Keys to be generated (default = 1)'
        required: false
        default: '1'
      mail:
        description: 'Choose the mail provider to generate license'
        required: true
        type: choice
        options:
        - 1secmail
        - hi2in
        - 10minutemail
        - guerrillamail
        - developermail
        default: developermail
  schedule:
    - cron: "0 */1 * * *"

jobs:
  GenerateKey:
    runs-on: ubuntu-latest
    steps:
      - name: Generate key
        run: |
          KEY=2
          MAIL=1secmail
          ACCOUNT=0
          git clone https://github.com/ShafiqSadat/ESET-KeyGen.git
          cd ESET-KeyGen
          sudo apt update
          sudo apt install python3-pip
          sudo pip install -r requirements.txt
          if [[ (${ACCOUNT} != 0) && (${KEY} != 0) ]]
          then
          (seq 1 $((ACCOUNT)) | xargs -I {} -P $((ACCOUNT)) python3 main.py --chrome --account --token ${{ secrets.TOKEN }} --email-api ${MAIL} --skip-webdriver-menu --skip-update-check) & (seq 1 $((KEY)) | xargs -I {} -P $((KEY)) python3 main.py --chrome --key --token ${{ secrets.TOKEN }} --email-api ${MAIL} --skip-webdriver-menu --skip-update-check)
          echo "Account:" >> $GITHUB_STEP_SUMMARY
          cat ./*ACCOUNTS.txt >> $GITHUB_STEP_SUMMARY
          echo -e "\nKey:" >> $GITHUB_STEP_SUMMARY
          cat ./*KEYS.txt >> $GITHUB_STEP_SUMMARY
          exit
          fi
          
          if [[ ${ACCOUNT} != 0 ]]
          then
          seq 1 $((ACCOUNT)) | xargs -I {} -P $((ACCOUNT)) python3 main.py --chrome --account --token ${{ secrets.TOKEN }} --email-api ${MAIL} --skip-webdriver-menu --skip-update-check
          echo -e "\nAccount:" >> $GITHUB_STEP_SUMMARY
          cat ./*ACCOUNTS.txt >> $GITHUB_STEP_SUMMARY
          fi
          
          if [[ ${KEY} != 0 ]]
          then
          seq 1 $((KEY)) | xargs -I {} -P $((KEY)) python3 main.py --chrome --key --token ${{ secrets.TOKEN }} --email-api ${MAIL} --skip-webdriver-menu --skip-update-check
          echo -e "\nKey:" >> $GITHUB_STEP_SUMMARY
          cat ./*KEYS.txt >> $GITHUB_STEP_SUMMARY
          fi